
        self.label_1 = wx.StaticText(self, wx.ID_ANY, ("Type school name or location identifier"))
        self.text_ctrl_1 = wx.TextCtrl(self, wx.ID_ANY, "")
        self.label_2 = wx.StaticText(self, wx.ID_ANY, ("Add a school year:"))
        self.spin_ctrl_1 = wx.SpinCtrl(self, wx.ID_ANY, "", min=0, max=100, style=wx.TE_PROCESS_ENTER)
        self.label_3 = wx.StaticText(self, wx.ID_ANY, ("/2016"))
        self.button_2 = wx.Button(self, wx.ID_EXIT, "")
        self.button_1 = wx.Button(self, wx.ID_APPLY, "")

        self.SetTitle("dialog_1")
        self.text_ctrl_1.SetMinSize((250, 20))
        self.text_ctrl_1.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.spin_ctrl_1.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.label_3.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))

        grid_sizer_1 = wx.FlexGridSizer(5, 1, 0, 0)
        grid_sizer_2 = wx.GridSizer(1, 3, 0, 0)
        grid_sizer_3 = wx.FlexGridSizer(1, 4, 0, 0)
        grid_sizer_1.Add(self.label_1, 0, wx.ALIGN_CENTER | wx.ALL, 15)
        grid_sizer_1.Add(self.text_ctrl_1, 0, wx.ALIGN_CENTER | wx.ALL, 15)
        grid_sizer_1.Add(self.label_2, 0, wx.ALIGN_CENTER | wx.ALL, 15)
        grid_sizer_3.Add((60, 20), 0, wx.ALIGN_CENTER | wx.ALL, 15)
        grid_sizer_3.Add(self.spin_ctrl_1, 0, wx.ALIGN_CENTER | wx.ALL, 15)
        grid_sizer_3.Add(self.label_3, 0, wx.ALIGN_CENTER | wx.ALL, 15)
        grid_sizer_1.Add(grid_sizer_3, 1, 0, 0)
        grid_sizer_2.Add(self.button_2, 0, wx.ALIGN_CENTER | wx.ALL, 15)
        grid_sizer_2.Add((100, 20), 0, wx.ALIGN_CENTER | wx.ALL, 15)
        grid_sizer_2.Add(self.button_1, 0, wx.ALIGN_CENTER | wx.ALL, 15)
        grid_sizer_1.Add(grid_sizer_2, 1, 0, 0)
        self.SetSizer(grid_sizer_1)
        grid_sizer_1.Fit(self)
        self.Layout()

